export const SET_PIZZAS = "SET_PIZZAS";
export const SET_LOADED = "SET_LOADED";
export const ADD_ELEMENT_TO_BASKET = "ADD_PIZZA_TO_BASKET";
export const REMOVE_BASKET_ITEM = "REMOVE_BASKET_ITEM";
export const PLUS_BASKET_ITEM = "PLUS_BASKET_ITEM";
export const MINUS_BASKET_ITEM = "MINUS_BASKET_ITEM";
