export { default as BlockFood } from "./BlockFood/BlockFood";
export { default as CardFood } from "./CardFood/CardFood";
export { default as CardSlider } from "./CardSlider/CardSlider";
export { default as DeliveryInfoBlock } from "./DeliveryInfoBlock/DeliveryInfoBlock";
export { default as Footer } from "./Footer/Footer";
export { default as Header } from "./Header/Header";
export { default as Menu } from "./Menu/Menu";
export { default as SliderBlock } from "./SliderBlock/SliderBlock";
export { default as BasketItem } from "./BasketItem/BasketItem";
